### ISSUE TITLE
[Bug] Circular dependencies have been introduced

### ISSUE THREAD

**Issue by aamcrae** [jonobr1/two.js#750]
**Describe the bug**
Since the last release (0.8.14), circular dependencies have been introduced to the codebase.
This is causing issues when two is used as part of a webpack bundle - the client is getting the following error:
Uncaught ReferenceError: Cannot access 'Path' before initialization
    at Module.Path (￼matrix.js:607:1)
    at ../../../node_modules/two.js/src/shapes/arc-segment.js (￼arc-segment.js:20:1)
    at __webpack_require__ (￼bootstrap:22:1)
    at fn (￼hot module replacement:61:1)
    at ../../../node_modules/two.js/src/group.js (￼events.js:189:1)
    at __webpack_require__ (￼bootstrap:22:1)
    at fn (￼hot module replacement:61:1)
    at ../../../node_modules/two.js/src/renderers/canvas.js (￼registry.js:57:1)
    at __webpack_require__ (￼bootstrap:22:1)
    at fn (￼hot module replacement:61:1)

**To Reproduce**
There are utilities to check for circular dependencies:

npx madge --circular --extensions js ./
Processed 68 files (5s) 

✖ Found 12 circular dependencies!

1) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js
2) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/arc-segment.js
3) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/circle.js
4) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/ellipse.js
5) src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/points.js
6) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/points.js
7) src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/points.js > src/utils/shape.js
8) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/polygon.js
9) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/rectangle.js
10) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/rounded-rectangle.js
11) src/path.js > src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/shapes/star.js
12) src/effects/texture.js > src/renderers/canvas.js > src/group.js > src/text.js

There is a webpack plugin that also checks for circular dependencies, and this finds the same issues:

WARNING in ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js

WARNING in ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js

WARNING in ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/path.js

WARNING in ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js

WARNING in ../../../node_modules/two.js/src/shapes/arc-segment.js -> ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/arc-segment.js

WARNING in ../../../node_modules/two.js/src/shapes/circle.js -> ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/circle.js

WARNING in ../../../node_modules/two.js/src/shapes/ellipse.js -> ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/ellipse.js

WARNING in ../../../node_modules/two.js/src/shapes/points.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/points.js

WARNING in ../../../node_modules/two.js/src/shapes/polygon.js -> ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/polygon.js

WARNING in ../../../node_modules/two.js/src/shapes/rectangle.js -> ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/rectangle.js

WARNING in ../../../node_modules/two.js/src/shapes/rounded-rectangle.js -> ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/rounded-rectangle.js

WARNING in ../../../node_modules/two.js/src/shapes/star.js -> ../../../node_modules/two.js/src/path.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/shapes/star.js

WARNING in ../../../node_modules/two.js/src/text.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/text.js

WARNING in ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js

WARNING in ../../../node_modules/two.js/src/utils/shape.js -> ../../../node_modules/two.js/src/effects/texture.js -> ../../../node_modules/two.js/src/utils/canvas-shim.js -> ../../../node_modules/two.js/src/renderers/canvas.js -> ../../../node_modules/two.js/src/group.js -> ../../../node_modules/two.js/src/utils/shape.js

**Expected behavior**
The client not to get ReferenceError errors.

**Screenshots**

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [X] Packaged software (e.g: ES6 imports, react, angular, vue.js) - webpack
- [ ] Running headless (usually Node.js)

**Desktop (please complete the following information):**
 - OS: Linux, ubuntu 24.10
 - Browser: Chrome
 - Version: 131.0.6778.204 (Official Build) (64-bit)

Other context:
The key linkage seems to be src/effects/texture.js > src/renderers/canvas.js > src/group.js

**Comment by aamcrae** [comment]
Just to confirm this has happened since v0.8.14:

git checkout tags/v0.8.14 -b rel
npx madge --circular --extensions js ./
Processed 68 files (3.8s) 

✔ No circular dependency found!

**Comment by aamcrae** [comment]
path.js { Path } -> effects/texture.js { Texture } -> group.gs { Group } -> {Star,Circle, Ellipse,...} -> path.js { Path }

**Comment by aamcrae** [comment]
The culprit seems to be CanvasShim in effects/texture.js
Commenting out the check for CanvasShim.Image in getImage removes all the circular dependencies.

**Comment by jonobr1** [comment]
Okay, I've published the latest version with a patch for this: https://www.npmjs.com/package/two.js

**Comment by aamcrae** [comment]
Thank you!
